### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Albert1912** [SemmiWest/HomeWork1#3]
https://github.com/SemmiWest/HomeWork1/blob/41255e318a189f6a0114f3de132869881b32bc82/HomeWork1/Program.cs#L4

Надо было делать ввод с консоли

**Comment by SemmiWest** [comment]
Здравствуйте. 
Сделать ввод с консоли и загрузить?
  
>Четверг, 23 марта 2023, 20:39 +07:00 от Albert1912 ***@***.***>:
> 
> 
>https://github.com/SemmiWest/HomeWork1/blob/41255e318a189f6a0114f3de132869881b32bc82/HomeWork1/Program.cs#L4
>Надо было делать ввод с консоли
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you are subscribed to this thread. Message ID:  <SemmiWest/HomeWork1/issues/3 @ github . com> 
 
 
Семен Заподойников

**Comment by Albert1912** [comment]
Добрый день. Нет не надо. На будущее
